---
- name: Stop & Uninstall Apache
  hosts: web
  become: true
  gather_facts: false

  tasks:

  - name: Stop Apache
    ansible.builtin.service:
      name: apache2
      state: stopped
      enabled: no 

  - name: Uninstall Apache
    ansible.builtin.apt:
      name: apache2
      autoremove: yes
      state: absent

- name: Stop & Uninstall MariaDB
  hosts: db
  become: true
  gather_facts: false

  tasks:

  - name: Stop MariaDB
    ansible.builtin.service: 
      name: mariadb
      state: stopped
      enabled: no

  - name: Uninstall MariaDB
    ansible.builtin.apt:
      name: mariadb-server
      autoremove: yes
      state: absent